print("EXERCISE 3")
print(" ")
print("I will now count my chickens:")
print ("Hens" , float(25+30/6))
print("Roosers",float(100-25*3%4))
print("Now I will count the eggs:")
print (float(3+2+1-5+4%2-1/4+6))
print("Is it true that 3+2 < 5-7 ?")
print(3+2<5-7)
print("What is 3+2?",float(3+2))
print("What is 5-7?",float(5-7))
print("Oh, that's why it's False.")
print("How about some more.")
print("Is it greater?", 5>-2)
print("Is it greater or equal?",5>=-2)
print("Is it less or equal?",5<=-2)
#To make a floating point number, use the command float()
#This will just add the decimal place
